### ISSUE TITLE
Rust formatting error on build

### ISSUE THREAD

**Issue by jon-torodash** [microsoft/qsharp#1799]
**Describe the bug**

Attempting to build from tip of master on a mac ARM (OS 12.3.1) using a fresh Python 3.12.4 virtual environment.

Running `python ./prereqs.py` shows:
```
Detected node.js version v18.19.0

Detected Rust version: rustc 1.80.0 (051478957 2024-07-21)

Detected cargo fmt version: rustfmt 1.7.0-stable (05147895 2024-07-21)

Detected cargo clippy version: clippy 0.1.80 (05147895 2024-07-21)

Detected wasm-pack version wasm-pack 0.13.0
```

**To Reproduce**

1. Run `python ./build.py` from the repository root

**Expected behavior**

Build passes lint check.

**Output**

```
Checking formatting...
All matched files use Prettier code style!
Running the cargo fmt and clippy checks
    Checking library v0.0.0 (/Users/myUser/Documents/Development/qsharp/library)
    Checking qsc_data_structures v0.0.0 (/Users/myUser/Documents/Development/qsharp/compiler/qsc_data_structures)
   Compiling mimalloc-sys v0.0.0 (/Users/myUser/Documents/Development/qsharp/allocator/mimalloc-sys)
   Compiling qsc v0.0.0 (/Users/myUser/Documents/Development/qsharp/compiler/qsc)
    Checking tinytemplate v1.2.1
    Checking noisy_simulator v0.0.0 (/Users/myUser/Documents/Development/qsharp/noisy_simulator)
   Compiling samples_test v0.0.0 (/Users/myUser/Documents/Development/qsharp/samples_test)
   Compiling qsc_wasm v0.0.0 (/Users/myUser/Documents/Development/qsharp/wasm)
    Checking libfuzzer-sys v0.4.7
error: lint group `pedantic` has the same priority (0) as a lint
  --> Cargo.toml:80:1
   |
80 | pedantic = "warn"
   | ^^^^^^^^   ------ has an implicit priority of 0
81 | unwrap_used = "warn"
   | ----------- has the same priority as this lint
   |
   = note: the order of the lints in the table is ignored by Cargo
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#lint_groups_priority
   = note: `#[deny(clippy::lint_groups_priority)]` on by default
help: to have lints override the group set `pedantic` to a lower priority
   |
80 | pedantic = { level = "warn", priority = -1 }
   |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: could not compile `library` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `qsc` (build script) due to 1 previous error
error: could not compile `qsc_wasm` (build script) due to 1 previous error
error: could not compile `mimalloc-sys` (build script) due to 1 previous error
error: could not compile `samples_test` (build script) due to 1 previous error
error: could not compile `noisy_simulator` (lib) due to 1 previous error
error: could not compile `qsc_data_structures` (lib) due to 1 previous error
error: could not compile `qsc_data_structures` (lib test) due to 1 previous error
Traceback (most recent call last):
  File "/Users/myUser/Documents/Development/qsharp/./build.py", line 179, in <module>
    subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'clippy', '--all-targets', '--all-features', '--', '-D', 'warnings']' returned non-zero exit status 101.
(venv) jontorodash@Jon-Work-Laptop qsharp (main) $ python ./build.py --help
```
**System information**

- Main branch at commit `8756d0dbfc24afa1da030a79b64048d4f97cebd7`
- mac ARM (OS 12.3.1) using a fresh Python 3.12.4 virtual environment
- For issues with extensions, the version of the IDE for which the problem occurs

**Additional context**

Obviously, the error is skippable with the `--no-check`, but I'd rather not have to do that.

**Comment by billti** [comment]
Probably a new Rust 1.80 clippy check, being this repo is still on 1.79.

**Comment by billti** [comment]
We've updated to Rust 1.80 now. Reopen if you still see issues.
