### ISSUE TITLE
Interpreter panic when error message contains a span from a previous line

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#596]
FIR structs have a `Span` associated with them ([example](https://github.com/microsoft/qsharp/blob/4f7e49ea6a48bd83ee1e7ee9fd8afeaf53962c84/compiler/qsc_fir/src/fir.rs#L663)). However we don't save any context about which `SourceMap`s these `Span`s actually came from. If a runtime error contains a `Span` ([example](https://github.com/microsoft/qsharp/blob/4f7e49ea6a48bd83ee1e7ee9fd8afeaf53962c84/compiler/qsc_eval/src/intrinsic.rs#L67C49-L67C49)), we assume that the span is associated with the _current_ line ([here](https://github.com/microsoft/qsharp/blob/4f7e49ea6a48bd83ee1e7ee9fd8afeaf53962c84/compiler/qsc/src/interpret/stateful.rs#L404C38-L404C38)). This assumption isn't always correct.

**Repro Steps**

1. `cargo build` to build the interpreter binary
2. Run `qsi` and run the following in *two separate lines*
```qsharp
operation Main() : Unit { Microsoft.Quantum.Random.DrawRandomInt(2,1); }
```
```qsharp
Main()
```

**Expected**
Properly formatted `EmptyRange` message about `DrawRandomInt`

**Actual**
Panic:

```
qsi$ operation Main() : Unit { Microsoft.Quantum.Random.DrawRandomInt(2,1); }
qsi$ Main()
Error: empty range
Call stack:
    at Microsoft.Quantum.Random.DrawRandomInt in random.qs
    at Main in <expression>

error: Qsc.Eval.EmptyRange

  × runtime error
  ╰─▶ empty range
thread 'main' panicked at 'failed printing to stderr: formatter error', library/std/src/io/stdio.rs:1019:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: std::io::stdio::print_to
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1019:9
   3: std::io::stdio::_eprint
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1106:5
   4: qsi::print_interpret_result
             at ./src/bin/qsi.rs:189:17
   5: qsi::repl
             at ./src/bin/qsi.rs:149:13
   6: qsi::main
             at ./src/bin/qsi.rs:125:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```

Found on commit 99c94d55de276eb9e6d6210104c3ec3f1a27d14b

**Comment by minestarks** [comment]
I can also repro this within a single line, when the `Span` refers to the stdlib.

```
qsi$ use q = Qubit(); CNOT(q,q)
```
```
Error: qubits in gate invocation are not unique
Call stack:
    at QIR.Intrinsic.__quantum__qis__cx__body in qir.qs
    at Microsoft.Quantum.Intrinsic.CNOT in intrinsic.qs

error: Qsc.Eval.QubitUniqueness

  × runtime error
  ╰─▶ qubits in gate invocation are not unique
thread 'main' panicked at 'failed printing to stderr: formatter error', library/std/src/io/stdio.rs:1019:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: std::io::stdio::print_to
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1019:9
   3: std::io::stdio::_eprint
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1106:5
   4: qsi::print_interpret_result
             at ./src/bin/qsi.rs:189:17
   5: qsi::repl
             at ./src/bin/qsi.rs:149:13
   6: qsi::main
             at ./src/bin/qsi.rs:125:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by minestarks** [comment]
Not limited to runtime errors - here's another repro with a compilation error:

```
qsi$ namespace Other { operation DumpMachine() : Unit { } }
qsi$ open Other;
qsi$ open Microsoft.Quantum.Diagnostics;
qsi$ DumpMachine()
error: Qsc.Resolve.Ambiguous

  × name error
  ╰─▶ `DumpMachine` could refer to the item in `Other` or `Microsoft.Quantum.Diagnostics`
thread 'main' panicked at 'failed printing to stderr: formatter error', library/std/src/io/stdio.rs:1019:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: std::io::stdio::print_to
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1019:9
   3: std::io::stdio::_eprint
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/io/stdio.rs:1106:5
   4: qsi::print_interpret_result
             at ./src/bin/qsi.rs:189:17
   5: qsi::repl
             at ./src/bin/qsi.rs:149:13
   6: qsi::main
             at ./src/bin/qsi.rs:125:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```

**Comment by minestarks** [comment]
Fixed the compiler error issues, but carried the remaining case (runtime error) over to a new bug at #654
